### ISSUE TITLE
App crash when Delta Slide value is less than 0 and Min Frequency value is greater than 0.30 (100% reproducible)

### ISSUE THREAD

**Issue by AliElSaleh** [raysan5/rfxgen#15]
This bug is 100% reproducible, follow these steps:

1. Open rfxgen.exe
2. Increase Min frequency value greater or equal to 0.30
3. Decrease Delta Slide value below 0
4. CRASH!

**Comment by raysan5** [comment]
did you compile latest sources? it should be already corrected...

**Comment by AliElSaleh** [comment]
I believe I did. I just cloned the repo and ran the program today. Did you test this bug with the latest source?

**Comment by raysan5** [comment]
Hi @AliElSaleh, yes, you're right. I already worked on a very similar bug some time ago...

**Comment by raysan5** [comment]
Issue seems related to `raudio`, raylib audio module, some parameters caused a division by 0 on a buffer.

Corrected in commit https://github.com/raysan5/raylib/commit/d7fd6e0f1a4106690af7901173f421ea2fb1ea40.

Please, let me know if it works.

**Comment by AliElSaleh** [comment]
The issue is still there. Can you rebuild the release applications so I can test it?

**Comment by raysan5** [comment]
@AliElSaleh Sorry, I'm a bit confused... how did you test rfxgen to report this issue? I mean, the only possible way is recompiling the program yourself, the available `rfxgen.exe` is almost one year old.

**Comment by AliElSaleh** [comment]
I've compiled from the latest sources and the issue has been fixed.

**Comment by raysan5** [comment]
Thanks for reporting! :)
